# Testing PAC in yaml format
environments:
  pensionsdags_1:
    environment_variables:
      PAYCHECK1: 19000
pipelines:
  pac1_socarb:
    group: pac1_workshop
    label_template: "socarb(${src[:6]})"
    materials:
      src:  # Name of material
        git: https://github.com/pm-gocd/socarb.git
        branch: master
        auto_update: false
    stages:
      - defaultStage: # Name of stage
          jobs:
            defaultJob: # Name of the job
              artifacts:
               - build:
                   source: output
              tasks:
              - exec:
                  command: "/bin/bash"
                  arguments:
                  - -x
                  - ./calc.sh

  pac1_lon:
    group: pac1_workshop
    label_template: "lon(${src[:6]})"
    materials:
      src:  # Name of material
        git: https://github.com/pm-gocd/lon.git
        branch: master
        auto_update: false
    stages:
      - defaultStage: # Name of stage
          jobs:
            defaultJob: # Name of the job
              artifacts:
               - build:
                   source: output
              tasks:
              - exec:
                  command: "/bin/bash"
                  arguments:
                  - -x
                  - ./calc.sh

  pac1_privatpension:
    group: pac1_workshop
    label_template: "pp(${src[:6]})-${pac1_lon}"
    materials:
      src:  # Name of material
        git: https://github.com/pm-gocd/privatpension.git
        branch: master
        auto_update: false
      pac1_lon:
        type: dependency
        pipeline: pac1_lon
        stage: defaultStage
    stages:
      - defaultStage: # Name of stage
          jobs:
            defaultJob: # Name of the job
              artifacts:
               - build:
                   source: output
              tasks:
              - fetch:
                  pipeline: pac1_lon
                  stage: defaultStage
                  job: defaultJob
                  is_file: no
                  source: output
                  destination: upstream
              - exec:
                  command: "/bin/bash"
                  arguments:
                  - -x
                  - ./calc.sh

  pac1_tjanstepension:
    group: pac1_workshop
    label_template: "tp(${src[:6]})-${pac1_lon}"
    materials:
      src:  # Name of material
        git: https://github.com/pm-gocd/tjanstepension.git
        branch: master
        auto_update: false
      pac1_lon:
        type: dependency
        pipeline: pac1_lon
        stage: defaultStage
    stages:
      - defaultStage: # Name of stage
          jobs:
            defaultJob: # Name of the job
              artifacts:
               - build:
                   source: output
              tasks:
              - fetch:
                  pipeline: pac1_lon
                  stage: defaultStage
                  job: defaultJob
                  is_file: no
                  source: output
                  destination: upstream
              - exec:
                  command: "/bin/bash"
                  arguments:
                  - -x
                  - ./calc.sh

  pac1_alderspensionsavgift:
    group: pac1_workshop
    label_template: "aldpa(${src[:6]})-${pac1_socarb}"
    materials:
      src:  # Name of material
        git: https://github.com/pm-gocd/alderspensionsavgift.git
        branch: master
        auto_update: false
      pac1_socarb:
        type: dependency
        pipeline: pac1_socarb
        stage: defaultStage
    stages:
      - defaultStage: # Name of stage
          jobs:
            defaultJob: # Name of the job
              artifacts:
               - build:
                   source: output
              tasks:
              - fetch:
                  pipeline: pac1_socarb
                  stage: defaultStage
                  job: defaultJob
                  is_file: no
                  source: output
                  destination: upstream
              - exec:
                  command: "/bin/bash"
                  arguments:
                  - -x
                  - ./calc.sh

  pac1_allmanpensionsavgift:
    group: pac1_workshop
    label_template: "almpa(${src[:6]})-${pac1_lon}"
    materials:
      src:  # Name of material
        git: https://github.com/pm-gocd/allmanpensionsavgift.git
        branch: master
        auto_update: false
      pac1_lon:
        type: dependency
        pipeline: pac1_lon
        stage: defaultStage
    stages:
      - defaultStage: # Name of stage
          jobs:
            defaultJob: # Name of the job
              artifacts:
               - build:
                   source: output
              tasks:
              - fetch:
                  pipeline: pac1_lon
                  stage: defaultStage
                  job: defaultJob
                  is_file: no
                  source: output
                  destination: upstream
              - exec:
                  command: "/bin/bash"
                  arguments:
                  - -x
                  - ./calc.sh

  pac1_arbetsgivaravgift-egenavgift:
    group: pac1_workshop
    label_template: "arba(${src[:6]})-${pac1_lon}"
    materials:
      src:  # Name of material
        git: https://github.com/pm-gocd/arbetsgivaravgift-egenavgift.git
        branch: master
        auto_update: false
      pac1_lon:
        type: dependency
        pipeline: pac1_lon
        stage: defaultStage
    stages:
      - defaultStage: # Name of stage
          jobs:
            defaultJob: # Name of the job
              artifacts:
               - build:
                   source: output
              tasks:
              - fetch:
                  pipeline: pac1_lon
                  stage: defaultStage
                  job: defaultJob
                  is_file: no
                  source: output
                  destination: upstream
              - exec:
                  command: "/bin/bash"
                  arguments:
                  - -x
                  - ./calc.sh

  pac1_pensionsratter:
    group: pac1_workshop
    label_template: "pr(${src[:6]})-${pac1_alderspensionsavgift}-${pac1_allmanpensionsavgift}-${pac1_arbetsgivaravgift-egenavgift}"
    materials:
      src:  # Name of material
        git: https://github.com/pm-gocd/pensionsratter.git
        branch: master
        auto_update: false
      pac1_alderspensionsavgift:
        type: dependency
        pipeline: pac1_alderspensionsavgift
        stage: defaultStage
      pac1_allmanpensionsavgift:
        type: dependency
        pipeline: pac1_allmanpensionsavgift
        stage: defaultStage
      pac1_arbetsgivaravgift-egenavgift:
        type: dependency
        pipeline: pac1_arbetsgivaravgift-egenavgift
        stage: defaultStage
    stages:
      - defaultStage: # Name of stage
          jobs:
            defaultJob: # Name of the job
              artifacts:
               - build:
                   source: output
              tasks:
              - fetch:
                  pipeline: pac1_alderspensionsavgift
                  stage: defaultStage
                  job: defaultJob
                  is_file: no
                  source: output
                  destination: upstream
              - fetch:
                  pipeline: pac1_allmanpensionsavgift
                  stage: defaultStage
                  job: defaultJob
                  is_file: no
                  source: output
                  destination: upstream
              - fetch:
                  pipeline: pac1_arbetsgivaravgift-egenavgift
                  stage: defaultStage
                  job: defaultJob
                  is_file: no
                  source: output
                  destination: upstream
              - exec:
                  command: "/bin/bash"
                  arguments:
                  - -x
                  - ./calc.sh
