# Testing PAC in yaml format
environments:
  pensionsdags_1:
    environment_variables:
      PAYCHECK1: 19000
pipelines:
  pac_1_lon:
    group: pac_1_workshop
    materials:
      src:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/pm-gocd/lon.git
        branch: master
        auto_update: false
    stages:
      - defaultStage: # name of stage
          jobs:
            defaultJob: # name of the job
              tasks:
              - exec:
                  command: "/bin/bash"
                  arguments:
                  - -x
                  - ./calc.sh

## Just testing the example configuration file from
## https://github.com/tomzo/gocd-yaml-config-example/blob/master/ci.gocd.yaml
#environments:
#  example:
#    environment_variables:
#      EXAMPLE_DEPLOYMENT: testing
#    pipelines:
#      - yaml-example
#pipelines:
#  yamlpipe1:
#    group: simple
#    materials:
#      mygit:  # this is the name of material
#        # says about type of material and url at once
#        git: http://my.example.org/mygit.git
#    stages:
#      - build: # name of stage
#          jobs:
#            build: # name of the job
#              tasks:
#               - exec: # indicates type of task
#                   command: make
#  "yaml-example": # definition of yaml-example pipeline
#    group: yaml-example
#    label_template: "${mygit[:8]}"
#    locking: off
#    materials:
#      mygit: # this is the name of material
#        # keyword git says about type of material and url at once
#        git: http://my.example.org/mygit.git
#        branch: ci
#      upstream:
#        # type is optional here, material type is implied based on presence of pipeline and stage fields
#        # type: dependency
#        pipeline: yamlpipe1
#        stage: build
#    stages: # list of stages in order
#      - build: # name of stage
#          clean_workspace: true
#          jobs:
#            csharp: # name of the job
#              resources:
#               - net45
#              artifacts:
#               - build:
#                   source: bin/
#                   destination: build
#               - test:
#                   source: tests/
#                   destination: test-reports/
#              tabs:
#                report: test-reports/index.html
#              tasks: # ordered list of tasks to execute in job csharp
#               - fetch:
#                   pipeline: yamlpipe1
#                   stage: build
#                   job: build
#                   source: test-bin/
#                   destination: bin/
#               - exec: # indicates type of task
#                   command: make
#                   arguments:
#                    - "VERBOSE=true"
